# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 03:27
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('Credit_Ledger', '0001_initial'), ('Credit_Ledger', '0002_auto_20170720_0051'), ('Credit_Ledger', '0003_auto_20170808_2156'), ('Credit_Ledger', '0004_auto_20170905_0019')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=30)),
                ('account_type', models.CharField(max_length=100)),
                ('user', models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
