# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=30),
        ),
    ]
